config/routes.rb
Vle::Application.routes.draw do
  resources :panchayats

  resources :blocks

  resources :divisions

  resources :districts

  resources :users  do
    get :confirm,:on=>:collection
    post :verification,:on=>:collection
    get :export,:on=>:collection
    get :export_csv,:on=>:collection
    get :pending,:on=>:collection
    get :pending_export,:on=>:collection
  end

  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/user.rb
class User < ActiveRecord::Base
  #Relations
  has_one :user_profile
  #Attributes for User Profile
  accepts_nested_attributes_for :user_profile, :allow_destroy => true
  #validations
  validates :name,:father_name,:dob,:gender, :presence => true, :length => {:maximum => 100}
  validates :mobile_number, :presence => true, :length => {:maximum => 10}#,:uniqueness => true
  validates :phone_number, :length => {:maximum => 10}
  validates :pin, :length => {:maximum => 6},:presence => true

  #Recent and Search
  class << self
    def recent
      order('id DESC').limit(4)
    end
    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ######## For SMS Gateway ##############
  require 'net/http'
  require 'uri'
####################################

  def index
    @users = User.search(params[:search]).paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @users }
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @user }
    end
  end

  def new
    @user = User.new
    @user.build_user_profile

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    @panchayat = UserProfile.where(:panchayat_id => params[:user][:user_profile_attributes][:panchayat_id])


    if @panchayat.blank?

      charset = %w{ 1 2 3 4 5 6 7 8 9 0}
      @user.verification_code = (0...7).map { charset.to_a[rand(charset.size)] }.join


      respond_to do |format|
        if @user.save
          sms_status
          format.html { redirect_to(confirm_users_path, :notice => 'Verification code sent to Your mobile. Please enter the code to complete the registration process') }
          format.xml { render :xml => @user, :status => :created, :location => @user }
        else
          format.html { render :action => "new" }
          format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
        end
      end
    else
      flash[:error] = "The panchayat Already Registered. Your registration cannot be accepted"
      redirect_to new_user_path

    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml { head :ok }
    end
  end

  def sms_status
    mobile = @user.mobile_number
    message = "Dear VLE, Your activation code for CSC Portal is "+@user.verification_code+".Please use this code to complete your registration.Vedavaag Systems Limited."
    url = "http://www.smsginger.com/sendhttp.php?user=33602&password=chaitu1479&mobiles=#{mobile}&message=#{message}&sender=VEDCSC&route=4"
    Net::HTTP.get_print URI.parse(URI.encode(url.strip))

  end

  def confirm
    render
  end

  def verification
    @user = User.where(:verification_code => params[:verification_code]).first

    if @user.blank?
      flash[:error] = "Invalid verification code. Please check once again"
      redirect_to confirm_users_path
    else
      if @user.approved?
        flash[:error] = "The code is already verified."
        redirect_to confirm_users_path
      else
        district =District.find(@user.user_profile.district_id)
        district.increment!(:dis_number)
        vle_code= "BR" + district.short_code+"%04d" % district.dis_number
        @user.user_profile.vle_code= vle_code
        @user.email = vle_code.downcase.to_s + "@vedavaagcsc.in"

        @user.approved = true
        @user.verification_date = Time.now.strftime('%d-%m-%Y')

        @user.save
        flash[:notice] = "Congratulations. The verification code approved. Your registration is completed"
        redirect_to new_user_path
      end
    end
  end

  def load_districts
    @load_districts = District.where(:division_id => (params[:id])).order("name ASC")
    respond_to do |format|
      format.js
    end
  end

  def load_blocks
    @load_blocks = Block.where(:district_id => (params[:id])).order("name ASC")
    respond_to do |format|
      format.js
    end

  end

  def load_panchayats
    @load_panchayats = Panchayat.where(:block_id => (params[:id])).order("name ASC")

    respond_to do |format|
      format.js
    end

  end

  def export
    @users = User.all
    html = render_to_string :layout => false
    kit = PDFKit.new(html, :orientation => 'Landscape', :page_size => 'A4')
    send_data(kit.to_pdf, :filename => "Users_List"+".pdf", :type => 'application/pdf')
  end

  def export_csv
    require 'csv'
    @users = User.order('approved ASC')
    outfile = "User Report" + Time.now.strftime("%d-%m-%Y") + ".csv"
    csv_data = CSV.generate do |csv|
      csv << ["Status", "Name",  "Mobile", "Division", "District", "Block", "Panchayat"]
      @users.each do |user|
        csv << [user.approved? ? 'A' : 'P', user.name.titleize,  user.mobile_number, user.user_profile.division.name.titleize, user.user_profile.district.name.titleize, user.user_profile.block_id? ? user.user_profile.block.name.titleize : 'None', user.user_profile.panchayat.name.titleize]
      end
    end
    send_data csv_data,
              :type => 'text/csv; charset=iso-8859-1; header=present',
              :disposition => "attachment; filename=#{outfile}"

  end
  def pending
    @users = User.where(:approved => false).search(params[:search]).paginate(:page => params[:page], :per_page => 20)
  end
  def pending_export
    @users = User.where(:approved => false)
    html = render_to_string :layout => false
    kit = PDFKit.new(html, :orientation => 'Landscape', :page_size => 'A4')
    send_data(kit.to_pdf, :filename => "Users_Pending_List"+".pdf", :type => 'application/pdf')

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="form-container">
  <% form_for([@user], :html => {:multipart => true}) do |f| %>
      <p class="legend">
        <strong>Note:</strong>
        Required fields are marked with an asterisk (<em>*</em>)
      </p>
      <fieldset>
        <div>
          <label for="name">
            Name<em>*</em>
          </label>
          <%= f.text_field :name, :id => "firstname", :class => "tipTip", :title => "Enter Full Name of the User", :size => 30 %>
          <script type="text/javascript">
              var firstname = new LiveValidation('firstname');
              firstname.add(Validate.Presence)
          </script>
        </div>
        <div>
          <label for="address1">
            Date of Birth<em>*</em>
          </label>
          <%= f.date_select :dob, :start_year => Date.current.year-18, :end_year => 1940, :order => [:day, :month, :year], :prompt => {:day => 'Day', :month => 'Month', :year => 'Year'} %>
          <%= image_tag 'icot.gif', :class => "tipTip1", :title => "Select User Birthday" %>
        </div>
        <div>
          <label for="application_number">
            Gender:<em>*</em>
          </label>
          <%= f.select :gender, options_for_select([["Male", "male"], ["Female", "female"]]), :prompt => "Select Gender" %>
          <script type="text/javascript">
              var user_gender = new LiveValidation('user_gender');
              user_gender.add(Validate.Presence)
          </script>

          <%= image_tag 'icot.gif', :class => "tipTip1", :title => "Select User Gender" %>
        </div>
        <div>
          <label for="name">
            Father/Husband Name<em>*</em>
          </label>
          <%= f.text_field :father_name, :id => "fn", :class => "tipTip", :title => "Enter Father/Husband Name.", :size => 30 %>
          <script type="text/javascript">
              var fn = new LiveValidation('fn');
              fn.add(Validate.Presence)
          </script>
        </div>
        <div>
          <label for="address1">
            H.No<em>*</em>
          </label>
          <%= f.text_field :address1, :id => "address1", :class => "tipTip", :title => "Enter Address", :size => 30 %>
          <script type="text/javascript">
              var address1 = new LiveValidation('address1');
              address1.add(Validate.Presence)
          </script>
        </div>
        <div>
          <label for="address2">
            Street
          </label>
          <%= f.text_field :address2, :class => "tipTip", :title => "Enter Address", :size => 30 %>
        </div>
        <div>
          <label for="address2">
            Area
          </label>
          <%= f.text_field :address3, :class => "tipTip", :title => "Enter Address", :size => 30 %>
        </div>
        <div>
          <label for="place">
            Name of the Village/Town<em>*</em>
          </label>
          <%= f.text_field :place, :id => "place", :class => "tipTip", :title => "Enter Name of the Village or Town", :size => 30 %>
          <script type="text/javascript">
              var place = new LiveValidation('place');
              place.add(Validate.Presence)
          </script>
        </div>
        <div>
          <label for="pin">
            PIN<em>*</em>
          </label>
          <%= f.text_field :pin, :id => "pin", :class => "tipTip", :title => "Enter PIN. Must Contain 6 Digits. Ex:800001", :size => 30 %>
          <script type="text/javascript">
              var pin = new LiveValidation('pin');
              pin.add(Validate.Presence);
              pin.add(Validate.Numericality, {
                  minimum:800001,
                  maximum:899999
              });
          </script>
        </div>
        <div>
          <label for="phone">
            Mobile<em>*</em>
          </label>
          <%= f.text_field :mobile_number, :id => "mn", :class => "tipTip", :title => "Enter Mobile Number. Must Contain 10 Digits. Ex:9885976490", :size => 30 %>
          <script type="text/javascript">
              var mn = new LiveValidation('mn');
              mn.add(Validate.Presence);
              mn.add(Validate.Numericality);
              mn.add(Validate.Length, {
                  is:10
              });
          </script>
        </div>
        <div>
          <label for="pin">
            Telephone/Alternative Mobile:
          </label>
          <%= f.text_field :phone_number, :class => "tipTip", :title => "Enter Telephone Number", :size => 30 %>
        </div>
        <%= render(:partial => 'user_profile', :locals => {:f => f}) %>
        <div class="buttonrow">
          <%= f.submit "Save Details", :class => "btnEdit",:disable=>"Please Wait..." %>
        </div>
      </fieldset>
  <% end %>
</div>

app/views/users/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Users Report</h3>
    <% if @users.blank? %>
        No Divisions Added Yet...
    <% else %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="text">
                  <%= link_to "Verifited Users - ( #{User.where(:approved => true).size} )", "#", :class=>'usuallink tipTipRight' %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="text">
                  <%= link_to "Pending Users - ( #{User.where(:approved => false).size} )", pending_users_path, :class=>'usuallink tipTipRight' %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
    <% end %>
  </div>
</div>

app/views/users/_user_profile.html.erb
<%= f.fields_for :user_profile do |profile| %>
    <div>
      <label for="bidding_zone_id">
        Division
        <em>*</em>
      </label>
      <%= profile.collection_select :division_id,Division.active.order("name ASC"), :id, :name,{:prompt =>'Select Division'} %>
      <%= image_tag 'icot.gif',:class=>"tipTip1",:title => "Select Division of User from the List" %>
      <script type="text/javascript">
          var user_user_profile_attributes_division_id = new LiveValidation('user_user_profile_attributes_division_id');
          user_user_profile_attributes_division_id.add(Validate.Presence)
      </script>
      <script type="text/javascript">
          $(document).ready(function() {
              $('#districts').hide();

              $('#user_user_profile_attributes_division_id').change(function() {
                  var data = $('#user_user_profile_attributes_division_id').val();
                  $.ajax({
                      type: "POST",
                      url: "load_districts/" + data,
                      data: data
                  });

              });
          });
      </script>
      <span id="ajax-loading"><%= image_tag('/images/icons/ajax-loader.gif') %></span>
    </div>
    <div id="districts">
      <label for="district_id">
        District
        <em>*</em>
      </label>
      <%= profile.collection_select :district_id, District.order("name ASC"),:id, :name,:prompt =>'Select District' %>

      <%= image_tag 'icot.gif',:class=>"tipTip1",:title => "Select District of User from the List" %>
      <script type="text/javascript">
          var user_user_profile_attributes_district_id = new LiveValidation('user_user_profile_attributes_district_id');
          user_user_profile_attributes_district_id.add(Validate.Presence)
      </script>
      <script type="text/javascript">
          $(document).ready(function() {
              $('#blocks').hide();
              $('#user_user_profile_attributes_district_id').change(function() {
                  var data = $('#user_user_profile_attributes_district_id').val();
                  $.ajax({
                      type: "POST",
                      url: "load_blocks/" + data,
                      data: data
                  });

              });
          });
      </script>

    </div>
    <div id="blocks">
      <label for="csc_block_id">
        Block<em>*</em>
      </label>
      <%= profile.collection_select :block_id, Block.order("name ASC"),:id, :name,:prompt =>'Select Block' %>
      <%= image_tag 'icot.gif',:class=>"tipTip1",:title => "Select Block of User from the List" %>
      <script type="text/javascript">
          var user_user_profile_attributes_block_id = new LiveValidation('user_user_profile_attributes_block_id');
          user_user_profile_attributes_block_id.add(Validate.Presence)
      </script>
      <script type="text/javascript">
          $(document).ready(function() {
              $('#panchayats').hide();
              $('#user_user_profile_attributes_block_id').change(function() {
                  var data = $('#user_user_profile_attributes_block_id').val();
                  $.ajax({
                      type: "POST",
                      url: "load_panchayats/" + data,
                      data: data
                  });

              });
          });
      </script>

    </div>
    <div id="panchayats">
      <label for="csc_block_id">
        Panchayat<em>*</em>
      </label>
      <%= profile.collection_select :panchayat_id, Panchayat.order("name ASC"),:id, :name,:prompt =>'Select Panchayat' %>
      <%= image_tag 'icot.gif',:class=>"tipTip1",:title => "Select Panchayat of User from the List" %>
      <script type="text/javascript">
          var user_user_profile_attributes_panchayat_id = new LiveValidation('user_user_profile_attributes_panchayat_id');
          user_user_profile_attributes_panchayat_id.add(Validate.Presence)
      </script>
    </div>
    <%= profile.hidden_field :state_id,:value=>"1" %>
<% end %>

app/views/users/confirm.html.erb
<% title "VEDAVAAG | VLE | Verification" %>
<h3>VEDAVAAG | VLE | VLE Verification</h3>

<div class="help_text">
  Area for VLE Verification. <br/>
  Enter your verification code received by SMS on Registered Mobile Number to complete your Registration.<br/>
  It will take 5-10 time to get SMS.
</div>
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= form_tag verification_users_path do -%>
      <table class="tablesorter" align="center">

        <tr>
          <td>
            <label for="vle_user">
              Enter Verification Code :
            </label>
          </td>

          <td>
            <%= text_field_tag :verification_code -%>
          </td>
        </tr>
        <tr>
          <td colspan='2' align="right">
            <%= submit_tag 'Submit' -%>
          </td>
        </tr>
      </table>
      <% end -%>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/export.html.erb
<h5 align="center"> List of VLE Registered</h5>
<table class="tablesorter1" align="center">
  <thead>
  <tr>
    <th>#</th>
    <th>Verified?</th>
    <th>Email</th>
    <th>Name</th>
    <th>Division</th>
    <th>District</th>
    <th>Block</th>
    <th>Panchayat</th>
    <th>Mobile</th>

  </tr>
  </thead>
  <% i=1 %>
  <% @users.each do |user| %>
      <tr>
        <td><%= i %></td>
        <td><%=  user.approved? ? "A" : "P" %></td>
        
        <td><%# user.email %></td>
        <td><%= user.name.titleize %></td>
        <% if user.user_profile.blank? %>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        <% else %>
            <% if user.user_profile.division_id? %>
                <td><%= user.user_profile.division.name.titleize %></td>
            <%else%>
                <td></td>
            <%end%>
            <% if user.user_profile.district_id? %>
                <td><%= user.user_profile.district.name.titleize %></td>
            <%else%>
                <td></td>
            <%end%>
            <% if user.user_profile.block_id? %>
                <td><%= user.user_profile.block.name.titleize %></td>
            <% else %>
                <td></td>
            <%end%>
            <% if user.user_profile.panchayat_id? %>
                <td><%= user.user_profile.panchayat.name.titleize %></td>
            <% else %>
                <td></td>
            <%end%>
        <% end %>
        <td><%= user.mobile_number %></td>

      </tr>
      <% i = i + 1 %>
  <% end %>

</table>

<style type="text/css">
    table.tablesorter1 {
        border-collapse: collapse;
        border: 1px solid #000000;
        font-family: Tahoma, verdana, helvetica, sans-serif;
        font-size: 14px;
    }

    table.tablesorter1 td, table.tablesorter1 th {
        border-collapse: collapse;
        border: 1px solid #000000;
        text-align: center;
    }

    h5 {
        font-family: Tahoma, verdana, helvetica, sans-serif;
    }

</style>

app/views/users/index.html.erb
<% title "VEDAVAAG | VLE" %>
<h3>VEDAVAAG | VLE | VLE Registrations</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Users. <br/>
  Along with creating, managing Users for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'Export PDF'), export_users_path, :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Export CSV'), export_csv_users_path, :class => 'btn-yellow' %>
  <%# link_to content_tag(:span, 'New Block'), blocks_path, :class => 'btn-yellow' %>
  <%# link_to content_tag(:span, 'New Panchayat'), panchayats_path, :class => 'btn-yellow' %>
</div>

<% if @users.blank? %>
    <div class="error_msg">
      OOPS!.. No Users are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter" id="myTable">
      <thead>
      <tr>
        <th>#</th>
        <th>Verified?</th>
        <th>Name</th>
        <th>Division</th>
        <th>District</th>
        <th>Block</th>
        <th>Panchayat</th>
        <th>Mobile</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @users.each do |user| %>
          <tr>
            <td><%= i %></td>
            <td><%= user.approved? ? image_tag('tick.gif') : image_tag('cross.gif') %>
            </td>
            <td><%= highlight(user.name.titleize, params[:search]) %></td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.division_id? ? user.user_profile.division.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.district_id? ? user.user_profile.district.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.block_id? ? user.user_profile.block.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.panchayat_id? ? user.user_profile.panchayat.name.titleize : 'N.A') %>
            </td>
            <td><%= user.mobile_number %></td>
            <td><%= user.created_at.strftime('%d-%m-%Y') %></td>
            <td>
              <%= link_to "View", user, :class => 'usuallink bold_text' %>

            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @users %> <%= will_paginate @users, :container => false %>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function () {
                $("#myTable").tablesorter({headers:{ 0:{ sorter:false}, 1:{ sorter:false}, 9:{ sorter:false}}}

                );

            }
    );
</script>

app/views/users/load_blocks.js.erb
$('#blocks').show();
$('#user_user_profile_attributes_block_id').empty();
$('#user_user_profile_attributes_block_id').append($("<option></option>").attr("value","").text('Select Block'));
<% for load_block in @load_blocks %>
$('#user_user_profile_attributes_block_id').append($("<option></option>").attr("value", '<%= load_block.id %>').text('<%= load_block.name.titleize %>'));
<% end %>

app/views/users/load_districts.js.erb
$('#districts').show();
$('#user_user_profile_attributes_district_id').empty();
$('#user_user_profile_attributes_district_id').append($("<option></option>").attr("value","").text('Select District'));
<% for load_district in @load_districts %>
$('#user_user_profile_attributes_district_id').append($("<option></option>").attr("value", '<%= load_district.id %>').text('<%= load_district.name.titleize %>'));
<% end %>

app/views/users/load_panchayats.js.erb
$('#panchayats').show();
$('#user_user_profile_attributes_panchayat_id').empty();
$('#user_user_profile_attributes_panchayat_id').append($("<option></option>").attr("value","").text('Select Panchayat'));
<% for load_panchayat in @load_panchayats %>
$('#user_user_profile_attributes_panchayat_id').append($("<option></option>").attr("value", '<%= load_panchayat.id %>').text('<%= load_panchayat.name.titleize %>'));
<% end %>

app/views/users/pending.html.erb
<% title "VEDAVAAG | VLE" %>
<h3>VEDAVAAG | VLE | VLE Registrations</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Users. <br/>
  Along with creating, managing Users for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'All Users'), users_path, :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'Export Pending'), pending_export_users_path, :class => 'btn-yellow' %>

</div>

<% if @users.blank? %>
    <div class="error_msg">
      OOPS!.. No Users are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter" id="myTable">
      <thead>
      <tr>
        <th>#</th>
        <th>Verified?</th>
        <th>Name</th>
        <th>Division</th>
        <th>District</th>
        <th>Block</th>
        <th>Panchayat</th>
        <th>Mobile</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @users.each do |user| %>
          <tr>
            <td><%= i %></td>
            <td><%= user.approved? ? image_tag('tick.gif') : image_tag('cross.gif') %>
            </td>
            <td><%= highlight(user.name.titleize, params[:search]) %></td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.division_id? ? user.user_profile.division.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.district_id? ? user.user_profile.district.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.block_id? ? user.user_profile.block.name.titleize : 'N.A') %>
            </td>
            <td>
              <%= user.user_profile.blank? ? 'N.A' : (user.user_profile.panchayat_id? ? user.user_profile.panchayat.name.titleize : 'N.A') %>
            </td>
            <td><%= user.mobile_number %></td>
            <td><%= user.created_at.strftime('%d-%m-%Y') %></td>
            <td>
              <%= link_to "View", user, :class => 'usuallink bold_text' %>

            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @users %> <%= will_paginate @users, :container => false %>
    </div>
<% end %>

<script type="text/javascript">
    $(document).ready(function () {
                $("#myTable").tablesorter({headers:{ 0:{ sorter:false}, 1:{ sorter:false}, 9:{ sorter:false}}}

                );

            }
    );
</script>

app/views/users/show.html.erb
<% title "VEDAVAAG | User" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>VEDAVAAG | View VLE Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Email</th>
          <td><%# @user.email %></td>
        </tr>
        <tr>
          <th width="20%">Name</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th width="20%">Father Name</th>
          <td><%= @user.father_name %></td>
        </tr>
        <tr>
          <th width="20%">Gender</th>
          <td><%= @user.gender.titleize %></td>
        </tr>
        <tr>
          <th width="20%">Date of Birth</th>
          <td><%= @user.dob? ? @user.dob.strftime('%d-%m-%Y') : "" %></td>
        </tr>
        <tr>
          <th width="20%">Address</th>
          <td><%= @user.address1? ? @user.address1.titleize : "" %></td>
        </tr>
        <tr>
          <th width="20%"></th>
          <td><%= @user.address2? ? @user.address2.titleize : "" %></td>
        </tr>
        <tr>
          <th width="20%"></th>
          <td><%= @user.address3? ? @user.address3.titleize : "" %></td>
        </tr>
        <tr>
          <th width="20%">Place</th>
          <td><%= @user.place? ? @user.place.titleize : "" %></td>
        </tr>
        <tr>
          <th width="20%">PIN</th>
          <td><%= @user.pin %></td>
        </tr>

        <tr>
          <th width="20%">Mobile</th>
          <td><%= @user.mobile_number %></td>
        </tr>
        <tr>
          <th width="20%">District</th>
          <td><%= @user.user_profile.district_id? ? @user.user_profile.district.name.titleize : 'N.A' %></td>
        </tr>
        <tr>
          <th width="20%">Block</th>
          <td><%= @user.user_profile.block_id? ? @user.user_profile.block.name.titleize : 'N.A' %></td>
        </tr>
        <tr>
          <th width="20%">Panchayat</th>
          <td><%= @user.user_profile.panchayat_id ? @user.user_profile.panchayat.name.titleize : 'N.A' %></td>
        </tr>
      </table>
      <div class="link_buttons">
        <%= link_to content_tag(:span, 'Back'), users_path, :class => 'btn-yellow'%>
      </div>

    </div>
  </div>
</div>