config/routes.rb
Vle::Application.routes.draw do
  resources :panchayats

  resources :blocks

  resources :divisions

  resources :districts

  resources :users  do
    get :confirm,:on=>:collection
    post :verification,:on=>:collection
    get :export,:on=>:collection
    get :export_csv,:on=>:collection
    get :pending,:on=>:collection
    get :pending_export,:on=>:collection
  end

  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/division.rb
class Division < ActiveRecord::Base
  has_many :districts
  has_many :blocks
  has_many :panchayats

  class << self
  def active
    where(:status => true ).order('name')
  end
  end

end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  # GET /divisions
  # GET /divisions.xml
  def index
    @divisions = Division.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @divisions }
    end
  end

  # GET /divisions/1
  # GET /divisions/1.xml
  def show
    @division = Division.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @division }
    end
  end

  # GET /divisions/new
  # GET /divisions/new.xml
  def new
    @division = Division.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @division }
    end
  end

  # GET /divisions/1/edit
  def edit
    @division = Division.find(params[:id])
  end

  # POST /divisions
  # POST /divisions.xml
  def create
    @division = Division.new(params[:division])

    respond_to do |format|
      if @division.save
        format.html { redirect_to(@division, :notice => 'Division was successfully created.') }
        format.xml  { render :xml => @division, :status => :created, :location => @division }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @division.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /divisions/1
  # PUT /divisions/1.xml
  def update
    @division = Division.find(params[:id])

    respond_to do |format|
      if @division.update_attributes(params[:division])
        format.html { redirect_to(@division, :notice => 'Division was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @division.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1
  # DELETE /divisions/1.xml
  def destroy
    @division = Division.find(params[:id])
    @division.destroy

    respond_to do |format|
      format.html { redirect_to(divisions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_form.html.erb
<%= simple_form_for(@division) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render 'form' %>

<%= link_to 'Show', @division %> |
<%= link_to 'Back', divisions_path %>

app/views/divisions/index.html.erb
<h1>Listing divisions</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @divisions.each do |division| %>
  <tr>
    <td><%= link_to 'Show', division %></td>
    <td><%= link_to 'Edit', edit_division_path(division) %></td>
    <td><%= link_to 'Destroy', division, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Division', new_division_path %>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render 'form' %>

<%= link_to 'Back', divisions_path %>

app/views/divisions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_division_path(@division) %> |
<%= link_to 'Back', divisions_path %>