config/routes.rb
Vle::Application.routes.draw do
  resources :panchayats

  resources :blocks

  resources :divisions

  resources :districts

  resources :users  do
    get :confirm,:on=>:collection
    post :verification,:on=>:collection
    get :export,:on=>:collection
    get :export_csv,:on=>:collection
    get :pending,:on=>:collection
    get :pending_export,:on=>:collection
  end

  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/block.rb
class Block < ActiveRecord::Base
  has_many :panchayats
  belongs_to :division
  belongs_to :district

  validates :division_id, :presence => true
  validates :district_id, :presence => true
  validates :name, :presence => true, :length => {:maximum => 100}

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        #where(:name.matches => "%#{query}%") #from meta_where gem
        joins(:division,:district).where({:name.matches => "%#{query}%"}|{:divisions => [:name.matches => "%#{query}%"]}| {:districts => [:name.matches => "%#{query}%"]})
      else
        scoped
      end
    end
    def active
      where(:status => true).order('name ASC')
    end
  end      # end of class self

end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  def index
    @blocks = Block.order("district_id ASC,name ASC").search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @blocks }
    end
  end

  def show
    @block = Block.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @block }
    end
  end

  def new
    @block = Block.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @block }
    end
  end

  def edit
    @block = Block.find(params[:id])
  end

  def create
    @block = Block.new(params[:block])

    respond_to do |format|
      if @block.save
        format.html { redirect_to(blocks_url, :notice => 'Block was successfully created.') }
        format.xml { render :xml => @block, :status => :created, :location => @block }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @block.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @block = Block.find(params[:id])

    respond_to do |format|
      if @block.update_attributes(params[:block])
        format.html { redirect_to(@block, :notice => 'Block was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @block.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @block = Block.find(params[:id])
    @block.destroy

    respond_to do |format|
      format.html { redirect_to(blocks_url) }
      format.xml { head :ok }
    end
  end

  def load_districts
    @load_districts = District.where(:division_id => params[:id]).order("name ASC")
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@block, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name, :label => "Name", :placeholder => "Block Name" %>
        <%= f.association :division, :collection => Division.all(:order => 'name'), :prompt => "Choose a Division", :label_method => lambda { |state| "#{state.name.titleize} " }, :label => "Select Division" %>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#district').hide();
                $('#block_division_id').change(function () {
                    var data = $('#block_division_id').val();
                    $.ajax({
                        type:"POST",
                        url:"load_districts/" + data,
                        data:data
                    });
                });
            });
        </script>
        <div id="district">
          <%= f.association :district, :collection => District.all(:order => 'name'), :prompt => "Choose a District", :label_method => lambda { |district| "#{district.name.titleize} " }, :label => "Select District" %>
        </div>

        <%= f.submit 'Save', :disable_with => 'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/blocks/edit.html.erb
<h1>Editing block</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<% title "VEDAVAAG | VLE" %>
<h3>VEDAVAAG | Blocks | Manage Blocks</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing blocks. <br/>
  Along with creating, managing Blocks for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'Users'), users_path, :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'New Block'), new_block_path, :class => 'btn-yellow' %>
</div>

<% if @blocks.blank? %>
    <div class="error_msg">
      OOPS!.. No Blocks are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter" id="myTable">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>District</th>
        <th>Division</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @blocks.each do |block| %>
          <tr>
            <td><%= i %></td>
            <td><%= highlight(block.name.titleize, params[:search]) %></td>
            <td><%= highlight(block.district.name.titleize, params[:search]) %></td>
            <td><%= highlight(block.division.name.titleize, params[:search]) %></td>
            <td>
              <%= link_to "View", block, :class => 'usuallink bold_text' %>

            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>

<% end %>

<script type="text/javascript">
    $(document).ready(function () {
                $("#myTable").tablesorter({headers:{ 0:{ sorter:false}, 4:{ sorter:false}}}

                );

            }
    );
</script>

app/views/blocks/load_districts.js.erb
$('#district').show();
$('#block_district_id').empty();
$('#block_district_id').append($("<option></option>").attr("value","").text('Select District'));
<% for load_district in @load_districts %>
$('#block_district_id').append($("<option></option>").attr("value", '<%= load_district.id %>').text('<%= load_district.name.titleize %>'));
<% end %>

app/views/blocks/new.html.erb
<% title "VEDAVAAG | Blocks " %>
<h3>VEDAVAAG | Blocks | Block Registration</h3>
<%= render 'form',:heading => 'Create New User' %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>