config/routes.rb
Vle::Application.routes.draw do
  resources :panchayats

  resources :blocks

  resources :divisions

  resources :districts

  resources :users  do
    get :confirm,:on=>:collection
    post :verification,:on=>:collection
    get :export,:on=>:collection
    get :export_csv,:on=>:collection
    get :pending,:on=>:collection
    get :pending_export,:on=>:collection
  end

  # root :to => "welcome#index"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/panchayat.rb
class Panchayat < ActiveRecord::Base
  belongs_to :block
  belongs_to :district
  belongs_to :division

  validates :division_id, :presence => true
  validates :district_id, :presence => true
  validates :block_id, :presence => true

  validates :name, :presence => true, :length => {:maximum => 100}

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        #where(:name.matches => "%#{query}%") #from meta_where gem
        joins(:division,:district,:block).where({:name.matches => "%#{query}%"}|{:divisions => [:name.matches => "%#{query}%"]}| {:districts => [:name.matches => "%#{query}%"]} | {:blocks => [:name.matches => "%#{query}%"]})
      else
        scoped
      end
    end
    def active
      where(:status => true).order('name ASC')
    end
  end      # end of class self

end

app/controllers/panchayats_controller.rb
class PanchayatsController < ApplicationController
  def index
    @panchayats = Panchayat.search(params[:search]).paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @panchayats }
    end
  end

  def show
    @panchayat = Panchayat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @panchayat }
    end
  end

  def new
    @panchayat = Panchayat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @panchayat }
    end
  end

  def edit
    @panchayat = Panchayat.find(params[:id])
  end

  def create
    @panchayat = Panchayat.new(params[:panchayat])
    @panchayat.state_id = 1

    respond_to do |format|
      if @panchayat.save
        format.html { redirect_to(panchayats_url, :notice => 'Panchayat was successfully created.') }
        format.xml  { render :xml => @panchayat, :status => :created, :location => @panchayat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @panchayat.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    @panchayat = Panchayat.find(params[:id])

    respond_to do |format|
      if @panchayat.update_attributes(params[:panchayat])
        format.html { redirect_to(@panchayat, :notice => 'Panchayat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @panchayat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /panchayats/1
  # DELETE /panchayats/1.xml
  def destroy
    @panchayat = Panchayat.find(params[:id])
    @panchayat.destroy

    respond_to do |format|
      format.html { redirect_to(panchayats_url) }
      format.xml  { head :ok }
    end
  end
  def load_districts
    @load_districts = District.where(:division_id => params[:id]).order("name ASC")
    respond_to do |format|
      format.js
    end
  end
  def load_blocks
    @load_blocks = Block.where(:district_id => params[:id]).order("name ASC")
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/panchayats_helper.rb
module PanchayatsHelper
end

app/views/panchayats/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@panchayat, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name, :label => "Name", :placeholder => "Panchayat Name" %>
        <%= f.association :division, :collection => Division.all(:order => 'name'), :prompt => "Choose a Division", :label_method => lambda { |state| "#{state.name.titleize} " }, :label => "Select Division" %>
        <script type="text/javascript">
            $(document).ready(function () {
                $('#district').hide();
                $('#panchayat_division_id').change(function () {
                    var data = $('#panchayat_division_id').val();
                    $.ajax({
                        type:"POST",
                        url:"load_districts/" + data,
                        data:data
                    });
                });
            });
        </script>
        <div id="district">
          <%= f.association :district, :collection => District.all(:order => 'name'), :prompt => "Choose a District", :label_method => lambda { |district| "#{district.name.titleize} " }, :label => "Select District" %>
          <script type="text/javascript">
              $(document).ready(function () {
                  $('#block').hide();
                  $('#panchayat_district_id').change(function () {
                      var data = $('#panchayat_district_id').val();
                      $.ajax({
                          type:"POST",
                          url:"load_blocks/" + data,
                          data:data
                      });
                  });
              });
          </script>

        </div>
        <div id="block">
          <%= f.association :block, :collection => Block.all(:order => 'name'), :prompt => "Choose a Block", :label_method => lambda { |district| "#{district.name.titleize} " }, :label => "Select Block" %>

        </div>
        <%= f.submit 'Save', :disable_with => 'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/panchayats/edit.html.erb
<h1>Editing panchayat</h1>

<%= render 'form' %>

<%= link_to 'Show', @panchayat %> |
<%= link_to 'Back', panchayats_path %>

app/views/panchayats/index.html.erb
<% title "VEDAVAAG | VLE" %>
<h3>VEDAVAAG | Panchayats | Manage Panchayats</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Panchayats. <br/>
  Along with creating, managing Panchayat for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'Users'), users_path, :class => 'btn-yellow' %>
  <%= link_to content_tag(:span, 'New Panchayat'), new_panchayat_path, :class => 'btn-yellow' %>
</div>

<% if @panchayats.blank? %>
    <div class="error_msg">
      OOPS!.. No Panchayats are Found in the System..!
    </div>
<% else %>
    <table class="tablesorter" id="myTable">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Block</th>
        <th>District</th>
        <th>Division</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @panchayats.each do |pan| %>
          <tr>
            <td><%= i %></td>
            <td><%= highlight(pan.name.titleize, params[:search]) %></td>
            <td><%= highlight(pan.block.name.titleize,params[:search]) %></td>
            <td><%= highlight(pan.district.name.titleize,params[:search]) %></td>
            <td><%= highlight(pan.division.name.titleize,params[:search]) %></td>
            <td>
              <%= link_to "View", pan, :class => 'usuallink bold_text' %>

            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @panchayats %> <%= will_paginate @panchayats, :container => false %>
    </div>

<% end %>

<script type="text/javascript">
    $(document).ready(function () {
                $("#myTable").tablesorter({headers:{ 0:{ sorter:false}, 4:{ sorter:false}}}

                );

            }
    );
</script>

app/views/panchayats/load_blocks.js.erb
$('#block').show();
$('#panchayat_block_id').empty();
$('#panchayat_block_id').append($("<option></option>").attr("value","").text('Select Block'));
<% for load_district in @load_blocks %>
$('#panchayat_block_id').append($("<option></option>").attr("value", '<%= load_district.id %>').text('<%= load_district.name.titleize %>'));
<% end %>

app/views/panchayats/load_districts.js.erb
$('#district').show();
$('#panchayat_district_id').empty();
$('#panchayat_district_id').append($("<option></option>").attr("value","").text('Select District'));
<% for load_district in @load_districts %>
$('#panchayat_district_id').append($("<option></option>").attr("value", '<%= load_district.id %>').text('<%= load_district.name.titleize %>'));
<% end %>

app/views/panchayats/new.html.erb
<% title "VEDAVAAG | Panchayats " %>
<h3>VEDAVAAG | Panchayats | Panchayat Registration</h3>
<%= render 'form',:heading => 'Create New User' %>

app/views/panchayats/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_panchayat_path(@panchayat) %> |
<%= link_to 'Back', panchayats_path %>